name: materials-property-modeling
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.21.0,<2.0.0  # Pin to NumPy 1.x for PyTorch compatibility
  - matplotlib>=3.3.0
  - seaborn>=0.11.0
  - pytorch>=1.9.0
  - cpuonly